<?php
/**
 * Plugin Name: Global Hill View RWA Portal
 * Description: Voter list lookup and RWA membership application portal with Aadhaar/payment uploads, correction requests, admin dashboard, CSV import/export, and membership card download.
 * Version: 1.2.0
 * Author: Global Hill View RWA
 */
if (!defined('ABSPATH')) { exit; }

class GHV_RWA_Portal {
    const VERSION = '1.2.0';
    const NONCE = 'ghv_rwa_nonce';
    private static $instance = null;
    public static function instance(){ if (!self::$instance) { self::$instance = new self(); } return self::$instance; }
    private function __construct(){
        register_activation_hook(__FILE__, array($this,'activate'));
        add_action('wp_enqueue_scripts', array($this,'frontend_assets'));
        add_shortcode('rwa_voter_portal', array($this,'shortcode'));
        add_action('wp_ajax_ghv_search_voters', array($this,'ajax_search'));
        add_action('wp_ajax_nopriv_ghv_search_voters', array($this,'ajax_search'));
        add_action('wp_ajax_ghv_submit_application', array($this,'submit_application'));
        add_action('wp_ajax_nopriv_ghv_submit_application', array($this,'submit_application'));
        add_action('wp_ajax_ghv_submit_correction', array($this,'submit_correction'));
        add_action('wp_ajax_nopriv_ghv_submit_correction', array($this,'submit_correction'));
        add_action('wp_ajax_ghv_download_card', array($this,'download_card'));
        add_action('wp_ajax_nopriv_ghv_download_card', array($this,'download_card'));
        add_action('admin_menu', array($this,'admin_menu'));
        add_action('admin_post_ghv_import_csv', array($this,'admin_import_csv'));
        add_action('admin_post_ghv_update_status', array($this,'admin_update_status'));
        add_action('admin_post_ghv_export', array($this,'admin_export'));
    }
    private function table($name){ global $wpdb; return $wpdb->prefix.'ghv_'.$name; }
    public function activate(){ $this->create_tables(); $this->maybe_seed_voters(); }
    private function create_tables(){
        global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; $charset = $wpdb->get_charset_collate();
        dbDelta("CREATE TABLE {$this->table('voters')} (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            source_id BIGINT UNSIGNED NULL,
            tower VARCHAR(50) DEFAULT '', flat VARCHAR(50) DEFAULT '', first_owner VARCHAR(255) DEFAULT '', second_owner VARCHAR(255) DEFAULT '', membership_no VARCHAR(100) DEFAULT '', eligible VARCHAR(50) DEFAULT '', discrepancy TEXT NULL, voted VARCHAR(50) DEFAULT '', raw_data LONGTEXT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (id), KEY tower (tower), KEY flat (flat), KEY membership_no (membership_no), KEY first_owner (first_owner(191))
        ) $charset;");
        dbDelta("CREATE TABLE {$this->table('applications')} (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            request_type VARCHAR(30) DEFAULT 'membership', status VARCHAR(30) DEFAULT 'pending', full_name VARCHAR(255) DEFAULT '', mobile VARCHAR(50) DEFAULT '', email VARCHAR(190) DEFAULT '', tower VARCHAR(50) DEFAULT '', flat VARCHAR(50) DEFAULT '', aadhaar_number VARCHAR(50) DEFAULT '', transaction_id VARCHAR(120) DEFAULT '', payment_receipt TEXT NULL, aadhaar_front TEXT NULL, aadhaar_back TEXT NULL, old_name VARCHAR(255) DEFAULT '', old_tower VARCHAR(50) DEFAULT '', old_flat VARCHAR(50) DEFAULT '', membership_no VARCHAR(100) DEFAULT '', correction_notes TEXT NULL, admin_notes TEXT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (id), KEY request_type (request_type), KEY status (status), KEY full_name (full_name(191)), KEY mobile (mobile)
        ) $charset;");
    }
    private function maybe_seed_voters(){ global $wpdb; $count = (int)$wpdb->get_var("SELECT COUNT(*) FROM {$this->table('voters')}"); if($count>0){ return; } $file = plugin_dir_path(__FILE__).'data/voters.csv'; if(file_exists($file)){ $this->import_csv_file($file); } }
    public function frontend_assets(){ wp_enqueue_style('ghv-rwa-style', plugin_dir_url(__FILE__).'assets/css/style.css', array(), self::VERSION); wp_enqueue_script('ghv-rwa-script', plugin_dir_url(__FILE__).'assets/js/script.js', array('jquery'), self::VERSION, true); wp_localize_script('ghv-rwa-script','ghvRwa', array('ajaxurl'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce(self::NONCE))); }
    public function shortcode(){ ob_start(); ?>
        <div class="ghv-portal"><h2 class="ghv-title">Global Hill View RWA Voter Search</h2><p class="ghv-muted">Search your name in the voter list by owner name, tower, or flat number.</p><form id="ghv-search-form"><div class="ghv-search-row"><input type="text" name="q" placeholder="Enter owner name, tower, or flat number" required><button class="ghv-btn" type="submit">Search</button></div></form><div id="ghv-results"></div></div>
        <?php return ob_get_clean(); }
    private function check_nonce(){ $nonce = isset($_REQUEST['nonce']) ? sanitize_text_field(wp_unslash($_REQUEST['nonce'])) : ''; if(!wp_verify_nonce($nonce, self::NONCE)){ wp_send_json_error(array('message'=>'Security check failed.')); } }
    public function ajax_search(){ $this->check_nonce(); global $wpdb; $q = isset($_POST['q']) ? sanitize_text_field(wp_unslash($_POST['q'])) : ''; if(strlen($q)<1){ wp_send_json_error(array('message'=>'Search term required.')); } $like = '%'.$wpdb->esc_like($q).'%'; $sql = $wpdb->prepare("SELECT * FROM {$this->table('voters')} WHERE first_owner LIKE %s OR second_owner LIKE %s OR tower LIKE %s OR flat LIKE %s OR membership_no LIKE %s ORDER BY first_owner ASC LIMIT 20", $like,$like,$like,$like,$like); $rows = $wpdb->get_results($sql, ARRAY_A); wp_send_json_success(array('found'=>!empty($rows), 'voters'=>$rows)); }
    private function upload_file($field){ if(empty($_FILES[$field]['name'])){ return ''; } require_once ABSPATH.'wp-admin/includes/file.php'; $allowed = array('jpg|jpeg|jpe'=>'image/jpeg','png'=>'image/png','gif'=>'image/gif','webp'=>'image/webp','pdf'=>'application/pdf'); $upload = wp_handle_upload($_FILES[$field], array('test_form'=>false,'mimes'=>$allowed)); if(isset($upload['error'])){ return new WP_Error('upload_error',$upload['error']); } return esc_url_raw($upload['url']); }
    public function submit_application(){ $this->check_nonce(); $this->save_request('membership'); }
    public function submit_correction(){ $this->check_nonce(); $this->save_request('correction'); }
    private function save_request($type){ global $wpdb; $required = array('full_name','mobile','tower','flat','aadhaar_number'); foreach($required as $r){ if(empty($_POST[$r])){ wp_send_json_error(array('message'=>'Please fill all required fields.')); } } if($type==='membership' && (empty($_POST['transaction_id']) || empty($_FILES['payment_receipt']['name']))){ wp_send_json_error(array('message'=>'Payment receipt and transaction ID are required.')); }
        $aadhaar_front = $this->upload_file('aadhaar_front'); if(is_wp_error($aadhaar_front)){ wp_send_json_error(array('message'=>$aadhaar_front->get_error_message())); }
        $aadhaar_back = $this->upload_file('aadhaar_back'); if(is_wp_error($aadhaar_back)){ wp_send_json_error(array('message'=>$aadhaar_back->get_error_message())); }
        $receipt = $type==='membership' ? $this->upload_file('payment_receipt') : ''; if(is_wp_error($receipt)){ wp_send_json_error(array('message'=>$receipt->get_error_message())); }
        $data = array(
            'request_type'=>$type, 'status'=>'pending', 'full_name'=>sanitize_text_field(wp_unslash($_POST['full_name'])), 'mobile'=>sanitize_text_field(wp_unslash($_POST['mobile'])), 'email'=>isset($_POST['email'])?sanitize_email(wp_unslash($_POST['email'])):'', 'tower'=>sanitize_text_field(wp_unslash($_POST['tower'])), 'flat'=>sanitize_text_field(wp_unslash($_POST['flat'])), 'aadhaar_number'=>sanitize_text_field(wp_unslash($_POST['aadhaar_number'])), 'transaction_id'=>isset($_POST['transaction_id'])?sanitize_text_field(wp_unslash($_POST['transaction_id'])):'', 'payment_receipt'=>$receipt, 'aadhaar_front'=>$aadhaar_front, 'aadhaar_back'=>$aadhaar_back, 'old_name'=>isset($_POST['old_name'])?sanitize_text_field(wp_unslash($_POST['old_name'])):'', 'old_tower'=>isset($_POST['old_tower'])?sanitize_text_field(wp_unslash($_POST['old_tower'])):'', 'old_flat'=>isset($_POST['old_flat'])?sanitize_text_field(wp_unslash($_POST['old_flat'])):'', 'membership_no'=>isset($_POST['membership_no'])?sanitize_text_field(wp_unslash($_POST['membership_no'])):'', 'correction_notes'=>isset($_POST['correction_notes'])?sanitize_textarea_field(wp_unslash($_POST['correction_notes'])):'', 'created_at'=>current_time('mysql'), 'updated_at'=>current_time('mysql')
        );
        $wpdb->insert($this->table('applications'), $data); $msg = $type==='membership' ? 'Membership application submitted successfully. RWA admin will verify your details.' : 'Correction request submitted successfully.'; wp_send_json_success(array('message'=>$msg)); }
    public function download_card(){ $this->check_nonce(); global $wpdb; $id = isset($_GET['id']) ? absint($_GET['id']) : 0; $v = $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->table('voters')} WHERE id=%d", $id), ARRAY_A); if(!$v){ wp_die('Record not found'); } header('Content-Type: text/html; charset=utf-8'); header('Content-Disposition: attachment; filename="GHV-Membership-Card-'.sanitize_file_name($v['membership_no']).'.html"'); echo '<!doctype html><html><head><meta charset="utf-8"><title>Membership Card</title><style>body{font-family:Arial;padding:30px}.card{width:520px;border:2px solid #0f766e;border-radius:18px;padding:24px}.title{font-size:24px;font-weight:800;color:#0f766e}.name{font-size:28px;font-weight:800;margin-top:20px}.row{margin:10px 0}.badge{display:inline-block;background:#ecfdf5;border:1px solid #86efac;border-radius:999px;padding:8px 12px;margin:5px}</style></head><body><div class="card"><div class="title">Global Hill View RWA</div><p>Membership / Voter Card</p><div class="name">'.esc_html($v['first_owner']).'</div><div class="row"><span class="badge">Tower: '.esc_html($v['tower']).'</span><span class="badge">Flat: '.esc_html($v['flat']).'</span></div><div class="row">Membership No: <strong>'.esc_html($v['membership_no']).'</strong></div><div class="row">Eligible Voter: <strong>'.esc_html($v['eligible']).'</strong></div><div class="row">Previous Voting: <strong>'.esc_html($v['voted']).'</strong></div></div><script>window.print();</script></body></html>'; exit; }
    public function admin_menu(){ add_menu_page('RWA Portal','RWA Portal','manage_options','ghv-rwa-dashboard',array($this,'admin_dashboard'),'dashicons-groups',26); add_submenu_page('ghv-rwa-dashboard','Dashboard','Dashboard','manage_options','ghv-rwa-dashboard',array($this,'admin_dashboard')); add_submenu_page('ghv-rwa-dashboard','Voter List','Voter List','manage_options','ghv-rwa-voters',array($this,'admin_voters')); add_submenu_page('ghv-rwa-dashboard','Membership Applications','Membership Applications','manage_options','ghv-rwa-applications',array($this,'admin_applications')); add_submenu_page('ghv-rwa-dashboard','Payments','Payments','manage_options','ghv-rwa-payments',array($this,'admin_payments')); add_submenu_page('ghv-rwa-dashboard','Import CSV','Import CSV','manage_options','ghv-rwa-import',array($this,'admin_import')); add_submenu_page('ghv-rwa-dashboard','Settings','Settings','manage_options','ghv-rwa-settings',array($this,'admin_settings')); }
    private function admin_header($title){ echo '<div class="wrap"><h1>'.esc_html($title).'</h1>'; }
    private function admin_footer(){ echo '</div>'; }
    public function admin_dashboard(){ global $wpdb; $v=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$this->table('voters')}"); $pending=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$this->table('applications')} WHERE status='pending'"); $apps=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$this->table('applications')} WHERE request_type='membership'"); $corr=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$this->table('applications')} WHERE request_type='correction'"); $this->admin_header('RWA Portal Dashboard'); echo '<div class="ghv-admin-cards"><div class="ghv-admin-card"><strong>'.$v.'</strong>Voters</div><div class="ghv-admin-card"><strong>'.$apps.'</strong>Applications</div><div class="ghv-admin-card"><strong>'.$corr.'</strong>Corrections</div><div class="ghv-admin-card"><strong>'.$pending.'</strong>Pending</div></div><p>Use the left menu to manage voter list, applications, payments, CSV import, and settings.</p>'; $this->admin_footer(); }
    public function admin_voters(){ global $wpdb; $q=isset($_GET['s'])?sanitize_text_field(wp_unslash($_GET['s'])):''; $where=''; $args=array(); if($q){ $like='%'.$wpdb->esc_like($q).'%'; $where='WHERE first_owner LIKE %s OR second_owner LIKE %s OR tower LIKE %s OR flat LIKE %s'; $args=array($like,$like,$like,$like); } $sql="SELECT * FROM {$this->table('voters')} $where ORDER BY id DESC LIMIT 200"; $rows=$args?$wpdb->get_results($wpdb->prepare($sql,$args),ARRAY_A):$wpdb->get_results($sql,ARRAY_A); $this->admin_header('Voter List'); echo '<form method="get"><input type="hidden" name="page" value="ghv-rwa-voters"><input type="search" name="s" value="'.esc_attr($q).'" placeholder="Search voters"><button class="button">Search</button> <a class="button" href="'.esc_url(admin_url('admin-post.php?action=ghv_export&type=voters&_wpnonce='.wp_create_nonce('ghv_export'))).'">Export CSV</a></form><br>'; $this->render_voter_table($rows); $this->admin_footer(); }
    private function render_voter_table($rows){ echo '<table class="widefat striped"><thead><tr><th>Name</th><th>Tower</th><th>Flat</th><th>Membership No</th><th>Eligible</th><th>Voted Earlier</th></tr></thead><tbody>'; foreach($rows as $r){ echo '<tr><td>'.esc_html($r['first_owner']).'<br><small>'.esc_html($r['second_owner']).'</small></td><td>'.esc_html($r['tower']).'</td><td>'.esc_html($r['flat']).'</td><td>'.esc_html($r['membership_no']).'</td><td>'.esc_html($r['eligible']).'</td><td>'.esc_html($r['voted']).'</td></tr>'; } echo '</tbody></table>'; }
    public function admin_applications(){ $this->render_requests('membership','Membership Applications'); }
    public function admin_payments(){ $this->render_requests('membership','Payments', true); }
    private function render_requests($type,$title,$payments=false){ global $wpdb; $rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM {$this->table('applications')} WHERE request_type=%s ORDER BY id DESC LIMIT 200",$type),ARRAY_A); $this->admin_header($title); echo '<p><a class="button" href="'.esc_url(admin_url('admin-post.php?action=ghv_export&type=applications&_wpnonce='.wp_create_nonce('ghv_export'))).'">Export Applications CSV</a></p><table class="widefat striped"><thead><tr><th>ID</th><th>Name</th><th>Contact</th><th>Flat</th><th>Aadhaar</th><th>Payment</th><th>Files</th><th>Status</th><th>Action</th></tr></thead><tbody>'; foreach($rows as $r){ echo '<tr><td>'.absint($r['id']).'</td><td>'.esc_html($r['full_name']).'</td><td>'.esc_html($r['mobile']).'<br>'.esc_html($r['email']).'</td><td>'.esc_html($r['tower']).' / '.esc_html($r['flat']).'</td><td>'.esc_html($r['aadhaar_number']).'</td><td>'.esc_html($r['transaction_id']).'</td><td>'; foreach(array('aadhaar_front'=>'Aadhaar Front','aadhaar_back'=>'Aadhaar Back','payment_receipt'=>'Receipt') as $k=>$label){ if(!empty($r[$k])) echo '<a target="_blank" href="'.esc_url($r[$k]).'">'.esc_html($label).'</a><br>'; } echo '</td><td><span class="ghv-status '.esc_attr($r['status']).'">'.esc_html($r['status']).'</span></td><td>'; foreach(array('approved'=>'Approve','rejected'=>'Reject','pending'=>'Pending') as $status=>$label){ echo '<a class="button button-small" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=ghv_update_status&id='.absint($r['id']).'&status='.$status),'ghv_update_status')).'">'.$label.'</a> '; } echo '</td></tr>'; } echo '</tbody></table>'; $this->admin_footer(); }
    public function admin_import(){ $this->admin_header('Import CSV'); echo '<p>Upload voter CSV with row_data JSON column. Existing voter records will be replaced.</p><form method="post" enctype="multipart/form-data" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="ghv_import_csv">'; wp_nonce_field('ghv_import_csv'); echo '<input type="file" name="voters_csv" accept=".csv" required> <button class="button button-primary">Import CSV</button></form>'; $this->admin_footer(); }
    public function admin_settings(){ $this->admin_header('Settings'); echo '<h2>Payment Details</h2><p><strong>GLOBAL HILL VIEW APARTMENT OWNERS WEL AS</strong><br>HDFC Bank<br>A/C: 50200061399909<br>IFSC: HDFC0003648<br>Branch: JMD Megapolis Sohna Road</p><p>Shortcode: <code>[rwa_voter_portal]</code></p>'; $this->admin_footer(); }
    public function admin_import_csv(){ if(!current_user_can('manage_options')) wp_die('Not allowed'); check_admin_referer('ghv_import_csv'); if(empty($_FILES['voters_csv']['tmp_name'])) wp_die('No file'); global $wpdb; $wpdb->query("TRUNCATE TABLE {$this->table('voters')}"); $count=$this->import_csv_file($_FILES['voters_csv']['tmp_name']); wp_safe_redirect(admin_url('admin.php?page=ghv-rwa-import&imported='.$count)); exit; }
    private function import_csv_file($file){ global $wpdb; $fh=fopen($file,'r'); if(!$fh){ return 0; } $headers=fgetcsv($fh); $count=0; while(($row=fgetcsv($fh))!==false){ $assoc=array(); foreach($headers as $i=>$h){ $assoc[$h]=isset($row[$i])?$row[$i]:''; } $json=isset($assoc['row_data'])?$assoc['row_data']:''; $data=json_decode($json,true); if(!is_array($data)){ continue; } $wpdb->insert($this->table('voters'), array('source_id'=>isset($assoc['id'])?absint($assoc['id']):0,'tower'=>sanitize_text_field($data['Tower']??''),'flat'=>sanitize_text_field((string)($data['Flat']??'')),'first_owner'=>sanitize_text_field($data['First Owner Name']??''),'second_owner'=>sanitize_text_field($data['Second Owner Name']??''),'membership_no'=>sanitize_text_field((string)($data['Membership Card & Share Certificate No']??'')),'eligible'=>sanitize_text_field($data['Elegible Voter']??($data['Eligible Voter']??'')),'discrepancy'=>sanitize_textarea_field($data['Discrepency']??''),'voted'=>sanitize_text_field($data['Voted Earlier']??''),'raw_data'=>wp_json_encode($data),'created_at'=>current_time('mysql'),'updated_at'=>current_time('mysql'))); $count++; } fclose($fh); return $count; }
    public function admin_update_status(){ if(!current_user_can('manage_options')) wp_die('Not allowed'); check_admin_referer('ghv_update_status'); global $wpdb; $id=isset($_GET['id'])?absint($_GET['id']):0; $status=isset($_GET['status'])?sanitize_key($_GET['status']):'pending'; if(!in_array($status,array('pending','approved','rejected'),true)){ $status='pending'; } $wpdb->update($this->table('applications'), array('status'=>$status,'updated_at'=>current_time('mysql')), array('id'=>$id)); wp_safe_redirect(wp_get_referer()?wp_get_referer():admin_url('admin.php?page=ghv-rwa-applications')); exit; }
    public function admin_export(){ if(!current_user_can('manage_options')) wp_die('Not allowed'); check_admin_referer('ghv_export'); global $wpdb; $type=isset($_GET['type'])?sanitize_key($_GET['type']):'voters'; $table=$type==='applications'?$this->table('applications'):$this->table('voters'); $rows=$wpdb->get_results("SELECT * FROM $table", ARRAY_A); header('Content-Type: text/csv; charset=utf-8'); header('Content-Disposition: attachment; filename="ghv-'.$type.'-'.date('Ymd-His').'.csv"'); $out=fopen('php://output','w'); if(!empty($rows)){ fputcsv($out,array_keys($rows[0])); foreach($rows as $row){ fputcsv($out,$row); } } fclose($out); exit; }
}
GHV_RWA_Portal::instance();
